// 双击按钮停止加热事件
// Created by mdmbct on 10/2/22.
//

#ifndef ESP8285HEATFRAMEWORK_DOUBLECLICKSTOPEVENT_H
#define ESP8285HEATFRAMEWORK_DOUBLECLICKSTOPEVENT_H

#endif //ESP8285HEATFRAMEWORK_DOUBLECLICKSTOPEVENT_H
